#!/bin/bash
go install -v github.com/bashtian/jsonutils/cmd/jsonutil
currentPath=$(pwd)"/model.go"

if command -v jsonutil > /dev/null 2>&1; then
    echo "jsonutil install success"
else
    echo "error: jsonutil not found. cannot download package"
    exit 1
fi

# create temp folder
tmpdir=$(mktemp -t -d gocorpora.XXXXXX)
cd $tmpdir || exit

# clone corpora repo
git clone https://github.com/dariusk/corpora.git
cd corpora || exit

rm -rf $currentPath
echo "package gocorpora" >> $currentPath
echo "/**" >> $currentPath
echo "*** The model is generated by script " >> $currentPath
echo "**/" >> $currentPath

res=$(find data -name "*.json")
for r in $res
do
  echo $r

  echo '{"data":' > gocorpora.tmp
  cat "$r" >> gocorpora.tmp
  echo '}' >> gocorpora.tmp
  mv gocorpora.tmp $r

  echo "// from "$r >> $currentPath
  jsonutil -f $r >> $currentPath
done;

# remote temp folder
rm -rf "$tmpdir"